"""initial_schema

Revision ID: 0a4791315fbf
Revises: a1b2c3d4e5f6
Create Date: 2026-04-08 19:09:50.026185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a4791315fbf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='chat_session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('reasoning_style', sa.String(length=100), nullable=True),
    sa.Column('position_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_agents_chat_session_id'), 'chat_agents', ['chat_session_id'], unique=False)
    op.create_table('chat_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='chat_turn_status'), nullable=False),
    sa.Column('current_round_no', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_turns_chat_session_id'), 'chat_turns', ['chat_session_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_chat_session_id'), 'documents', ['chat_session_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_turn_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('chat_agent_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('started', 'success', 'failed', name='llm_call_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_turn_id'], ['chat_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_chat_turn_id'), 'llm_calls', ['chat_turn_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_round_id'), 'llm_calls', ['round_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_turn_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=True),
    sa.Column('chat_agent_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sa.Enum('user', 'agent', 'judge', 'system', name='sender_type'), nullable=False),
    sa.Column('message_type', sa.Enum('user_input', 'agent_response', 'critique', 'final_summary', 'system_notice', name='message_type'), nullable=False),
    sa.Column('visibility', sa.Enum('visible', 'internal', name='message_visibility'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_agent_id'], ['chat_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_turn_id'], ['chat_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_session_id'), 'messages', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_turn_id'), 'messages', ['chat_turn_id'], unique=False)
    op.create_index(op.f('ix_messages_round_id'), 'messages', ['round_id'], unique=False)
    op.drop_table('user_settings')
    op.drop_constraint(op.f('rounds_debate_id_fkey'), 'rounds', type_='foreignkey')
    op.drop_index(op.f('ix_agents_debate_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_debates_user_id'), table_name='debates')
    op.drop_table('debates')
    
    # Create ENUMs before adding them to existing tables
    from sqlalchemy.dialects import postgresql
    postgresql.ENUM('initial', 'critique', 'final', name='round_type').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('started', 'completed', 'failed', name='round_status').create(op.get_bind(), checkfirst=True)

    op.add_column('rounds', sa.Column('chat_turn_id', sa.Uuid(), nullable=False))
    op.add_column('rounds', sa.Column('round_type', sa.Enum('initial', 'critique', 'final', name='round_type'), nullable=False))
    op.add_column('rounds', sa.Column('status', sa.Enum('started', 'completed', 'failed', name='round_status'), nullable=False))
    op.add_column('rounds', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rounds', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rounds', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('rounds', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_rounds_debate_id'), table_name='rounds')
    op.create_index(op.f('ix_rounds_chat_turn_id'), 'rounds', ['chat_turn_id'], unique=False)
    op.create_foreign_key(None, 'rounds', 'chat_turns', ['chat_turn_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rounds', 'debate_id')
    op.drop_column('rounds', 'data')
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'name')
    op.add_column('rounds', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('rounds', sa.Column('debate_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.create_foreign_key(op.f('rounds_debate_id_fkey'), 'rounds', 'debates', ['debate_id'], ['id'])
    op.drop_index(op.f('ix_rounds_chat_turn_id'), table_name='rounds')
    op.create_index(op.f('ix_rounds_debate_id'), 'rounds', ['debate_id'], unique=False)
    op.drop_column('rounds', 'updated_at')
    op.drop_column('rounds', 'created_at')
    op.drop_column('rounds', 'ended_at')
    op.drop_column('rounds', 'started_at')
    op.drop_column('rounds', 'status')
    op.drop_column('rounds', 'round_type')
    op.drop_column('rounds', 'chat_turn_id')
    op.create_table('agents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('debate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], name=op.f('agents_debate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey'))
    )
    op.create_index(op.f('ix_agents_debate_id'), 'agents', ['debate_id'], unique=False)
    op.create_table('debates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('debates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('debates_pkey'))
    )
    op.create_index(op.f('ix_debates_user_id'), 'debates', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=50), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_messages_round_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_turn_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_calls_round_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_chat_turn_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_chat_session_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_turns_chat_session_id'), table_name='chat_turns')
    op.drop_table('chat_turns')
    op.drop_index(op.f('ix_chat_agents_chat_session_id'), table_name='chat_agents')
    op.drop_table('chat_agents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
