"""update_tables

Revision ID: 2106cbaf8a6e
Revises: 8b6f2e13a01f
Create Date: 2026-05-18 17:38:34.697377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '2106cbaf8a6e'
down_revision: Union[str, None] = '8b6f2e13a01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    embedding_exists = conn.execute(
        sa.text(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'document_chunks'
              AND column_name = 'embedding'
            """
        )
    ).fetchone()

    if embedding_exists:
        return

    has_pgvector = conn.execute(
        sa.text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")
    ).fetchone() is not None

    if has_pgvector:
        op.add_column(
            "document_chunks",
            sa.Column("embedding", VECTOR(dim=768), nullable=True),
        )
    else:
        op.add_column(
            "document_chunks",
            sa.Column("embedding", sa.JSON(), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
